function rxLog = RX_SDR_OFDM_Channel_Sounding(config)
%RX_SDR_OFDM_CHANNEL_SOUNDING Continuous OFDM channel sounding receiver for Pluto SDR.
%
%   rxLog = RX_SDR_OFDM_Channel_Sounding(config) listens to the Pluto SDR,
%   aligns and demodulates OFDM sounding frames generated by the companion
%   transmitter, and reports basic performance diagnostics. The function is
%   designed to run for a finite duration so that it can be orchestrated from
%   a test harness (for example via PARFEVAL). Helper functions from the
%   MathWorks end-to-end OFDM example perform synchronization, channel
%   estimation, and decoding.
%
%   CONFIG is an optional struct supporting the following fields:
%       OFDMParams        - struct overriding default OFDM parameters
%       DataParams        - struct overriding default data parameters
%       RadioID           - Pluto SDR identifier (default "usb:1")
%       CenterFrequency   - RF center frequency in Hz (default 3.0e9)
%       Gain              - Pluto RX gain in dB (default 30)
%       RunDuration       - Total run time in seconds (default 10, Inf allowed)
%       MaxFrames         - Maximum number of successfully decoded frames (Inf)
%       DisplayUpdates    - Logical flag to print status messages (default true)
%
%   Example:
%       rxCfg = struct('RunDuration', 15, ...
%                      'DisplayUpdates', false);
%       futureRx = parfeval(@RX_SDR_OFDM_Channel_Sounding, 1, rxCfg);
%
%   The helper functions in this folder must be on the MATLAB path.
%
%   Copyright 2024

if nargin < 1 || isempty(config)
    config = struct();
end

% Reset helper persistent state (important when running on parallel workers)
clear helperOFDMRx helperOFDMRxSearch helperOFDMRxFrontEnd;

defaultOFDM = struct( ...
    'FFTLength',              128, ...
    'CPLength',               32, ...
    'NumSubcarriers',         72, ...
    'Subcarrierspacing',      30e3, ...
    'PilotSubcarrierSpacing', 9, ...
    'channelBW',              3e6);

defaultData = struct( ...
    'modOrder',       2, ...
    'coderate',       "1/2", ...
    'numSymPerFrame', 30, ...
    'numFrames',      10000, ...
    'enableScopes',   true, ...
    'verbosity',      false);

rxOptions = struct( ...
    'RadioID',         "usb:1", ...
    'CenterFrequency', 3.0e9, ...
    'Gain',            60, ...
    'RunDuration',     60, ...
    'MaxFrames',       inf, ...
    'DisplayUpdates',  true);

OFDMParams = mergeStruct(defaultOFDM, getfieldwithdefault(config,'OFDMParams',struct()));
dataParams = mergeStruct(defaultData, getfieldwithdefault(config,'DataParams',struct()));

rxOptions.RadioID         = getfieldwithdefault(config,'RadioID',rxOptions.RadioID);
rxOptions.CenterFrequency = getfieldwithdefault(config,'CenterFrequency',rxOptions.CenterFrequency);
rxOptions.Gain            = getfieldwithdefault(config,'Gain',rxOptions.Gain);
rxOptions.RunDuration     = getfieldwithdefault(config,'RunDuration',rxOptions.RunDuration);
rxOptions.MaxFrames       = getfieldwithdefault(config,'MaxFrames',rxOptions.MaxFrames);
rxOptions.DisplayUpdates  = getfieldwithdefault(config,'DisplayUpdates',rxOptions.DisplayUpdates);

validateattributes(rxOptions.RunDuration, {'double'},{'scalar','real','>=',0});
validateattributes(rxOptions.MaxFrames, {'double'},{'scalar','real','>=',0});

% Derive common OFDM parameters
[sysParam, txParam, knownPayload] = helperOFDMSetParamsSDR(OFDMParams, dataParams);
sampleRate = sysParam.scs * sysParam.FFTLen;
symLen = sysParam.FFTLen + sysParam.CPLen;
frameLen = symLen * sysParam.numSymPerFrame;
sysParam.timingAdvance = sysParam.txWaveformSize;
sysParam.frameNum = 0;

% Instantiate Pluto SDR receiver
rxRadio = sdrrx('Pluto', 'RadioID', rxOptions.RadioID);
rxRadio.BasebandSampleRate = sampleRate;
rxRadio.CenterFrequency = rxOptions.CenterFrequency;
rxRadio.GainSource = 'Manual';
rxRadio.Gain = rxOptions.Gain;
rxRadio.SamplesPerFrame = frameLen;
rxRadio.OutputDataType = 'double';
rxRadio.EnableBurstMode = false;

% Initialize processing chain
rxObj = helperOFDMRxInit(sysParam);
rxKnownBits = knownPayload(:);
errorRate = comm.ErrorRate;

if dataParams.enableScopes
    rxSpectrumScope = spectrumAnalyzer( ...
        'Name',         'Received Signal Spectrum', ...
        'Title',        'Received OFDM Waveform', ...
        'SpectrumType', 'Power', ...
        'FrequencySpan','Full', ...
        'SampleRate',   sampleRate, ...
        'ShowLegend',   true, ...
        'ChannelNames', {'Received'});
    constDiag = comm.ConstellationDiagram(2, ...
        "ChannelNames",{'Header','Data'}, ...
        "ReferenceConstellation",{qammod(0:1,2,UnitAveragePower=true), ...
                                  qammod(0:txParam.modOrder-1,txParam.modOrder,UnitAveragePower=true)}, ...
        "ShowLegend",true);
    channelPlot = dsp.ArrayPlot( ...
        'Title','Estimated Channel Magnitude', ...
        'YLabel','|H|', ...
        'XLabel','Subcarrier Index', ...
        'XOffset',1, ...
        'YLimits',[0 2], ...
        'ShowGrid',true);
else
    rxSpectrumScope = [];
    constDiag = [];
    channelPlot = [];
end

cleanupObj = onCleanup(@() releaseRxResources(rxRadio, errorRate, rxSpectrumScope, constDiag, channelPlot)); %#ok<NASGU>

if rxOptions.DisplayUpdates
    fprintf('Listening for OFDM sounding frames on %s ...\n', rxOptions.RadioID);
end

runDuration = rxOptions.RunDuration;
startTime = tic;
framesDecoded = 0;
berHistory = [];
meanChannelMagHistory = [];
lockHistory = [];
lastDiagnostics = struct();

while shouldContinue(runDuration, startTime) && framesDecoded < rxOptions.MaxFrames
    rxSamples = rxRadio();
    if isempty(rxSamples)
        if rxOptions.DisplayUpdates
            warning('No samples received from Pluto SDR. Check RF link and gain settings.');
        end
        continue;
    end

    if ~isempty(rxSpectrumScope)
        rxSpectrumScope(rxSamples);
    end

    rxFrontEndOut = helperOFDMRxFrontEnd(rxSamples, sysParam, rxObj);

    sysParam.frameNum = sysParam.frameNum + 1;
    [rxBits, isConnected, toff, rxDiagnostics] = helperOFDMRx(rxFrontEndOut, sysParam, rxObj);
    sysParam.timingAdvance = toff;

    if ~isConnected || isempty(rxBits)
        lockHistory(end+1) = false; %#ok<AGROW>
        reset(errorRate);
        continue;
    end

    rxBits = rxBits(:);
    currentBER = NaN;
    if numel(rxBits) == numel(rxKnownBits)
        berStats = errorRate(rxKnownBits, rxBits);
        currentBER = berStats(1);
    end

    latestChannelMag = [];
    if isfield(rxDiagnostics,'estChannel') && ~isempty(rxDiagnostics.estChannel) ...
            && size(rxDiagnostics.estChannel,1) >= sysParam.usedSubCarr
        latestBlock = rxDiagnostics.estChannel(end-sysParam.usedSubCarr+1:end,:);
        if ~isempty(latestBlock)
            latestChannelMag = abs(latestBlock(:,1));
            if ~isempty(channelPlot)
                channelPlot(latestChannelMag.');
            end
        end
    end

    if ~isempty(constDiag) && isfield(rxDiagnostics,'rxConstellationHeader') ...
            && isfield(rxDiagnostics,'rxConstellationData') ...
            && ~isempty(rxDiagnostics.rxConstellationHeader) ...
            && ~isempty(rxDiagnostics.rxConstellationData)
        constDiag(complex(rxDiagnostics.rxConstellationHeader(:)), ...
                  complex(rxDiagnostics.rxConstellationData(:)));
    end

    framesDecoded = framesDecoded + 1;
    lockHistory(end) = true;
    berHistory(end+1) = currentBER; %#ok<AGROW>
    if ~isempty(latestChannelMag)
        meanChannelMagHistory(end+1) = mean(latestChannelMag); %#ok<AGROW>
    else
        meanChannelMagHistory(end+1) = NaN; %#ok<AGROW>
    end
    lastDiagnostics = rxDiagnostics;

    if rxOptions.DisplayUpdates
        if isnan(currentBER)
            fprintf('Frame %d locked (BER unavailable). Mean |H| = %g\n', ...
                sysParam.frameNum, meanChannelMagHistory(end));
        else
            fprintf('Frame %d locked: BER = %g, mean |H| = %g\n', ...
                sysParam.frameNum, currentBER, meanChannelMagHistory(end));
        end
    end
end

elapsedTime = toc(startTime);

rxLog = struct( ...
    'FramesDecoded',          framesDecoded, ...
    'BERHistory',             berHistory, ...
    'MeanChannelMagHistory',  meanChannelMagHistory, ...
    'LockHistory',            lockHistory, ...
    'ElapsedTime',            elapsedTime, ...
    'RunDurationTarget',      runDuration, ...
    'RadioID',                rxOptions.RadioID, ...
    'CenterFrequency',        rxOptions.CenterFrequency, ...
    'Gain',                   rxOptions.Gain, ...
    'OFDMParams',             OFDMParams, ...
    'DataParams',             dataParams, ...
    'LastDiagnostics',        lastDiagnostics);

end

%% Local helper functions
function tf = shouldContinue(runDuration, startTime)
if isfinite(runDuration)
    tf = toc(startTime) < runDuration;
else
    tf = true;
end
end

function out = mergeStruct(defaults, overrides)
out = defaults;
if isempty(overrides)
    return;
end
fields = fieldnames(overrides);
for idx = 1:numel(fields)
    out.(fields{idx}) = overrides.(fields{idx});
end
end

function value = getfieldwithdefault(s, fieldName, defaultValue)
if isstruct(s) && isfield(s, fieldName)
    value = s.(fieldName);
else
    value = defaultValue;
end
end

function releaseRxResources(radioObj, errorRateObj, spectrumScope, constDiagScope, channelPlotObj)
try %#ok<TRYNC>
    release(spectrumScope);
end
try %#ok<TRYNC>
    release(constDiagScope);
end
try %#ok<TRYNC>
    release(channelPlotObj);
end
try %#ok<TRYNC>
    release(radioObj);
end
try %#ok<TRYNC>
    release(errorRateObj);
end
clear helperOFDMRx helperOFDMRxSearch helperOFDMRxFrontEnd;
clear helperOFDMSetParamsSDR;
end

